packs <- c("shiny", "shinydashboard", "DT", "tidyr", "dashboardthemes", "gt", "PASWR2", "plotly")
renv::install(packs)
library(shiny)
library(shinydashboard)
library(DT)
library(tidyr)
library(dashboardthemes)
library(gt)
library(PASWR2)
library(plotly)
renv::snapshot()
